name: Build Fabric Mod

on:
  push:
    branches:
      - master  # Der Workflow wird bei einem Push zum master-Branch ausgeführt

jobs:
  build:
    runs-on: ubuntu-latest  # Der Workflow läuft auf einem Ubuntu-Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Holt den Code aus dem Repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Verwenden Sie Temurin für JDK

      - name: Build Fabric Mod
        run: ./gradlew build  # Verwenden Sie gradlew zum Build
