name: Build Fabric Mod

on:
  push:
    branches:
      - master  # Der Workflow wird ausgelöst, wenn Sie auf den 'master' Branch pushen

jobs:
  build:
    runs-on: ubuntu-latest  # Der Workflow läuft auf einem Ubuntu-Server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Dieser Schritt holt den Code aus dem Repository

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Installiert die benötigte Java-Version
        with:
          java-version: '17'  # Geben Sie die Java-Version hier an

      - name: Build Fabric Mod
        run: ./gradlew build  # Baut den Mod
